[package]
name = "web3-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2.0"
eyre = "0.6"
tokio = { version = "1.32", features = ["full"] } # remember to add full features, in order to use async main